DROP TABLE STORE; 
DROP TABLE EMPLOYEE; 
DROP TABLE DEPARTMENT; 
DROP TABLE REGISTER; 
DROP TABLE INVENTORY; 
DROP TABLE SHIPMENT; 
DROP TABLE PRODUCT; 
DROP TABLE SUPPLIER; 
DROP TABLE SHIPMENT_CONTAINS; 
DROP TABLE MANAGES_DEPT; 
DROP TABLE SUPERVISES;


CREATE TABLE STORE  ( 
	StoreID INT NOT NULL, 
	Name VARCHAR(20) NOT  NULL, 
	Address VARCHAR(30) NOT  NULL, 
	City VARCHAR(15) NOT  NULL, 
	State VARCHAR(2) NOT  NULL, 
	PRIMARY KEY (StoreID)
); 

CREATE TABLE DEPARTMENT  ( 
	DepartmentID INT NOT NULL, 
	SID INT NOT NULL, 
	Name VARCHAR(10) NOT  NULL, 
	Num_of_employees INT, 
	PRIMARY KEY (DepartmentID), 
	FOREIGN KEY (SID) REFERENCES STORE(StoreID)
); 

CREATE TABLE REGISTER  ( 
	Register_number INT NOT NULL, 
	Cash DECIMAL(3, 2),
	PRIMARY KEY (Register_number), 
	CONSTRAINT NotNegative CHECK (Cash >= 0)
); 

CREATE TABLE EMPLOYEE  ( 
	EmployeeID INT NOT NULL, 
	Employee_type VARCHAR(10) NOT NULL, 
	Salary DECIMAL(8, 2) NOT  NULL, 
	First_name VARCHAR(10) NOT NULL, 
	Last_name VARCHAR(10) NOT NULL, 
	Reg_num INT, 
	DeptID INT NOT NULL, 
	PRIMARY KEY (EmployeeID), 
	FOREIGN KEY (DeptID) REFERENCES DEPARTMENT(DepartmentID), 
	FOREIGN KEY (Reg_num) REFERENCES REGISTER(Register_num),
	CONSTRAINT MaxSalary CHECK (Salary <= 100000.00), 
	CONSTRAINT NotNegative CHECK (Salary >= 0)
); 

CREATE TABLE INVENTORY  ( 
	SID INT NOT NULL, 
	InventoryID INT NOT NULL, 
	PRIMARY KEY (SID, InventoryID), 
	FOREIGN KEY (SID) REFERENCES STORE(StoreID)
); 

CREATE TABLE SUPPLIER  ( 
	SupplierID INT NOT NULL, 
	Supplier_name VARCHAR(15), 
	PRIMARY KEY (SupplierID)
); 

CREATE TABLE SHIPMENT  ( 
	ShipmentID INT NOT NULL, 
	SupID INT, 
	Date_created DATE, 
	Date_delivered DATE, 
	SID INT NOT  NULL, 
	PRIMARY KEY (ShipmentID), 
	FOREIGN KEY (SID) REFERENCES STORE(StoreID), 
	CONSTRAINT DateOrder CHECK (Date_created <= Date_delivered)
); 

CREATE TABLE PRODUCT  ( 
	Serial_number INT NOT NULL, 
	Category VARCHAR(20), 
	Price DECIMAL(4, 2) NOT  NULL, 
	Name VARCHAR(30), 
	Stock INT, 
	Expiration DATE, 
	InvID INT NOT NULL, 
	PRIMARY KEY (Serial_number), 
	FOREIGN KEY (InvID) REFERENCES INVENTORY(InventoryID), 
	CONSTRAINT StockAmount CHECK (Stock >= 0)
); 

CREATE TABLE SHIPMENT_CONTAINS  (
	SID INT NOT NULL,
	PSN INT NOT NULL,
	ShID INT NOT NULL,
	Quantity INT,
	PRIMARY KEY (SID, PSN, ShID),
	FOREIGN KEY(SID) REFERENCES STORE(StoreID),
	FOREIGN KEY(PSN) REFERENCES PRODUCT(Serial_Number),
	FOREIGN KEY(ShID) REFERENCES SHIPMENT(ShipmentID)
 ); 

CREATE TABLE MANAGES_DEPT  ( 
	EID INT NOT NULL, 
	DID INT NOT NULL, 
	SID INT NOT NULL, 
	Start_date DATE NOT  NULL, 
	PRIMARY KEY (EID, DID, SID), 
	FOREIGN KEY (EID) REFERENCES EMPLOYEE(EmployeeID), 
	FOREIGN KEY (SID) REFERENCES STORE(StoreID), 
	FOREIGN KEY (DID) REFERENCES DEPARTMENT(DepartmentID)
); 

CREATE TABLE SUPERVISES  ( 
	EID INT NOT NULL, 
	SupID INT NOT NULL, 
	PRIMARY KEY (EID, SupID), 
	FOREIGN KEY (EID) REFERENCES EMPLOYEE(EmployeeID), 
	FOREIGN KEY (SupID) REFERENCES EMPLOYEE(EmployeeID)
);
